/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sismaps;

import dao.ProjetoDao;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import modelo.Projeto;

/**
 *
 * @author Gledson
 */
public class FrmProjetoConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProjetoConsulta
     */
    ProjetoDao dao = new ProjetoDao();
    List<Projeto> projetos = new ArrayList<>();
    Projeto proj;

    public FrmProjetoConsulta() {
        initComponents();
        this.proj = new Projeto();
        this.projetos = dao.carregarTodos();
        carregarTabela();

    }

    private void carregarTabela() {

        //List<Projeto> projetos;
        //projetos = dao.carregarTodos();
        ProjetoTableModel tabela = new ProjetoTableModel(projetos);
        jProjetoTable.setModel(tabela);
        jProjetoTable.setRowHeight(30);
        jProjetoTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        jProjetoTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        jProjetoTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        jProjetoTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        jProjetoTable.getColumnModel().getColumn(3).setPreferredWidth(300);
        jProjetoTable.getColumnModel().getColumn(4).setPreferredWidth(600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jProjetoTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();

        jProjetoTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jProjetoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jProjetoTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jProjetoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProjetoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jProjetoTable);

        jLabel1.setText("Cod. Projeto:");

        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });
        txtConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void txtConsultarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyReleased
        // TODO add your handling code here:
        if (txtConsultar.getText().length() > 5) {
            this.projetos = dao.carregarPorCodProjeto(txtConsultar.getText().toUpperCase().toString());
            carregarTabela();
        }

    }//GEN-LAST:event_txtConsultarKeyReleased

    private void jProjetoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProjetoTableMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() > 1) {
            this.proj = this.projetos.get(jProjetoTable.convertRowIndexToModel(jProjetoTable.getSelectedRow()));
            try {
                java.awt.Desktop.getDesktop().open( new File( this.proj.getCaminho() ) );  
                
                //JOptionPane.showMessageDialog(this, this.proj.getCaminho(),
                  //      "Informação", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(FrmProjetoConsulta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jProjetoTableMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jProjetoTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
