/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sismaps;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gledson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalDesktop = new javax.swing.JDesktopPane();
        mnMenuBar = new javax.swing.JMenuBar();
        mnPrincipal = new javax.swing.JMenu();
        mnCadProjetos = new javax.swing.JMenuItem();
        mnRequerente = new javax.swing.JMenuItem();
        mnAutor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnConsultarProjeto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnPrincipal.setText("Cadastro");

        mnCadProjetos.setText("Projetos QGIS");
        mnCadProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadProjetosActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnCadProjetos);

        mnRequerente.setText("Requerente");
        mnPrincipal.add(mnRequerente);

        mnAutor.setText("Autor");
        mnPrincipal.add(mnAutor);
        mnPrincipal.add(jSeparator1);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        mnPrincipal.add(mnSair);

        mnMenuBar.add(mnPrincipal);

        jMenu1.setText("Consulta");

        mnConsultarProjeto.setText("Consultar Projeto");
        mnConsultarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarProjetoActionPerformed(evt);
            }
        });
        jMenu1.add(mnConsultarProjeto);

        mnMenuBar.add(jMenu1);

        setJMenuBar(mnMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalDesktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadProjetosActionPerformed
        // TODO add your handling code here:
        
        ViewProjeto p = new ViewProjeto();
        principalDesktop.add(p);
        try {
            p.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        p.show();
        
    }//GEN-LAST:event_mnCadProjetosActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnConsultarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarProjetoActionPerformed
        // TODO add your handling code here:
        
        FrmProjetoConsulta p = new FrmProjetoConsulta();
        principalDesktop.add(p);
        try {
            p.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        p.show();
        
    }//GEN-LAST:event_mnConsultarProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnAutor;
    private javax.swing.JMenuItem mnCadProjetos;
    private javax.swing.JMenuItem mnConsultarProjeto;
    private javax.swing.JMenuBar mnMenuBar;
    private javax.swing.JMenu mnPrincipal;
    private javax.swing.JMenuItem mnRequerente;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JDesktopPane principalDesktop;
    // End of variables declaration//GEN-END:variables
}
