package modelo;
// Generated 22/10/2013 11:33:27 by Hibernate Tools 3.2.1.GA

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alocacao generated by hbm2java
 */
@Entity
@Table(name = "alocacao", schema = "public")
public class Alocacao implements java.io.Serializable {

    private int id;
    private String descricao;
    private List<Requerente> requerentes;

    public Alocacao() {
    }

    public Alocacao(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }

    public Alocacao(int id, String descricao, List<Requerente> requerentes) {
        this.id = id;
        this.descricao = descricao;
        this.requerentes = requerentes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "descricao", nullable = false, length = 80)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "alocacao")
    public List<Requerente> getRequerentes() {
        return this.requerentes;
    }

    public void setRequerentes(List<Requerente> requerentes) {
        this.requerentes = requerentes;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Alocacao other = (Alocacao) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }
    
    
}
