package modelo;
// Generated 22/10/2013 11:33:27 by Hibernate Tools 3.2.1.GA

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Requerente generated by hbm2java
 */
@Entity
@Table(name = "requerente", schema = "public")
public class Requerente implements java.io.Serializable {

    private int id;
    private Alocacao alocacao;
    private String nome;
    private List<Projeto> projetos;

    public Requerente() {
    }

    public Requerente(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }

    public Requerente(int id, Alocacao alocacao, String nome, List<Projeto> projetos) {
        this.id = id;
        this.alocacao = alocacao;
        this.nome = nome;
        this.projetos = projetos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "alocacao_id")
    public Alocacao getAlocacao() {
        return this.alocacao;
    }

    public void setAlocacao(Alocacao alocacao) {
        this.alocacao = alocacao;
    }

    @Column(name = "nome", nullable = false, length = 80)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "requerente")
    public List<Projeto> getProjetos() {
        return this.projetos;
    }

    public void setProjetos(List<Projeto> projetos) {
        this.projetos = projetos;
    }

    @Override
    public String toString() {
        return getNome() + " - "+getAlocacao().getDescricao(); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Requerente other = (Requerente) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }
    
    
}
